# Generated by Django 3.1.4 on 2020-12-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.person'),
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.person'),
        ),
        migrations.AddField(
            model_name='community',
            name='member',
            field=models.ManyToManyField(to='funding.Person'),
        ),
    ]
