# Generated by Django 3.1.4 on 2020-12-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20201206_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='location',
        ),
        migrations.AddField(
            model_name='community',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='community',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
