# Generated by Django 3.1.4 on 2020-12-05 16:31

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('target_amout', models.IntegerField(default=0)),
                ('funded_amout', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('option_num', models.IntegerField(default=1)),
                ('option_1_name', models.CharField(blank=True, max_length=30)),
                ('option_1_price', models.IntegerField(default=0)),
                ('option_2_name', models.CharField(blank=True, max_length=30)),
                ('option_2_price', models.IntegerField(default=0)),
                ('option_3_name', models.CharField(blank=True, max_length=30)),
                ('option_3_price', models.IntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_point', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=14)),
                ('category', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=20)),
                ('certificate', models.ImageField(blank=True, upload_to='')),
                ('base_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_num', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('Funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.funding')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.person')),
            ],
        ),
        migrations.AddField(
            model_name='funding',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funding.person'),
        ),
    ]
